services:
  db:
    image: postgres:16
    container_name: logshield-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logshield_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: logshield-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/logshield_db

  frontend:
    build: ./frontend
    container_name: logshield-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: